development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # this one works after deployment on heroku

  # url: redis://localhost:3333/cable
  # REDISTOGO_URL:            redis://redistogo:44f3a8bea48d9c08ed06e00b708d9db2@cod.redistogo.com:10043/
  url: redis://redistogo:44f3a8bea48d9c08ed06e00b708d9db2@cod.redistogo.com:10043/
  channel_prefix: codersappserver_production
# url: <%= ENV["REDIS_URL"] %>
